name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:8.7-jdk17
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew build